language: erlang
script: mix test
otp_release:
  - R16B
before_install:
  - mkdir -p vendor/elixir
  - wget -q https://github.com/elixir-lang/elixir/releases/download/v0.10.1/v0.10.1.zip && unzip -qq v0.10.1.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"